config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root            to: 'pages#home'
  get 'contact',  to: 'pages#contact'
  get 'about',    to: 'pages#about'
  get 'ask',      to: 'pages#ask'
  get 'answer',   to: 'pages#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def contact
    @contacts = %w[Bob Sheila Hank Eric]
    if params[:contact_name].present?
      @contacts = @contacts.select do |name|
        name.downcase == params[:contact_name].downcase
      end
    end
  end

  def about
    @today_date = Date.today.strftime('%d %b')
  end

  def answer
    answer1 = "I don't care, get dressed and go to work!"
    answer2 = 'Silly question, get dressed and go to work!'
    answer3 = 'Great!'
    # create a loop
    # ask a question
    # if the question does not end with a ? then state @answer1
    # if the question ends with a ? then state answer2
    # if the question = "I am going to work" then reply answer3
    # end the loop
    dumb_question = params[:question]
    if dumb_question.present?
      if dumb_question.downcase == 'i am going to work right now!'
        @answer = answer3
      elsif dumb_question.include? '?'
        @answer = answer2
      else
        @answer = answer1
      end
    end
  end

  def ask
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <nav>
      <h2>Navigation</h2>
      <ul>
        <li><%= link_to "Ask", ask_path %></li>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path%></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About us </h1>
<p> We are not good with Rails </p>
<!-- ER tags / icecream cone -->
<p><%= @today_date %></p>

app/views/pages/answer.html.erb
<h1> Are you wasting my time today? </h1>

<%= @answer %>

app/views/pages/ask.html.erb
<h1>Bakamon Coaching</h1>
<p> Ask your coach anything: </p>
<form action="/answer" method="get">
  <input type="text" name="question" placeholder="ask anything..">
  <input type="submit">
</form>

app/views/pages/contact.html.erb
<h1> Contacts </h1>
<form action="/contact" method="get">
  <input type="text" name="contact_name" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<ul>
 <% @contacts.each do |contact| %>
  <li><%= contact %></li>
 <% end %>
</ul>

app/views/pages/home.html.erb
<h1> Bakamon Coaching </h1>